server:
  port: 8080

spring:
  application:
    name: demo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai # useSSL=true 解决JDBC版本与MySQL版本不兼容问题
    username: root
    password: 123456
    druid:
      # 连接池配置(通常来说，只需要修改initialSize、minIdle、maxActive
      # 如果用Oracle，则把poolPreparedStatements配置为true，mysql可以配置为false。分库分表较多的数据库，建议配置为false。removeabandoned不建议在生产环境中打开如果用SQL Server，建议追加配置)
      initial-size: 5 # 初始化物理连接个数
      min-idle: 2 # 连接池中最小空闲连接数
      max-active: 20 # 连接池中最大的活跃连接数
      max-wait: 60000 # 配置获取连接等待超时的时间
      pool-prepared-statements: false # 开启缓存preparedStatement(PSCache)
      max-pool-prepared-statement-per-connection-size: -1 # 启用PSCache后，指定每个连接上PSCache的大小
      test-on-borrow: false # 申请连接时不检测连接是否有效
      test-on-return: false # 归还连接时不检测连接是否有效
      test-while-idle: true # 如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      validation-query: SELECT 'x'
      time-between-eviction-runs-millis: 60000 # 检测连接的间隔时间，若连接空闲时间 >= minEvictableIdleTimeMillis，则关闭物理连接
      min-evictable-idle-time-millis: 300000 # 连接保持空闲而不被驱逐的最小时间
      filter: config,stat # 配置监控统计拦截的filters（不配置则监控界面sql无法统计），监控统计filter:stat，日志filter:log4j，防御sql注入filter:wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=false; # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      web-stat-filter:
        enabled: true # 是否启用StatFilter默认值true
        url-pattern: /*
        exclusions: /*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*
        session-stat-enable: false
        session-stat-max-count: 1000
        principal-session-name: admin # 从session中获取身份标识
        principal-cookie-name: admin
        profile-enable: true
      # StatViewServlet配置
      #展示Druid的统计信息,StatViewServlet的用途包括：
      #   1.提供监控信息展示的html页面
      #   2.提供监控信息的JSON API
      stat-view-servlet:
        enabled: true # 是否启用StatViewServlet默认值true
        url-pattern: /druid/* # 根据配置中的url-pattern来访问内置监控页面
        reset-enable: false # 禁止手动重置监控数据
        login-username: admin # 设置监控页面的登录名和密码
        login-password: admin
        #StatViewSerlvet展示出来的监控信息比较敏感，是系统运行的内部情况，如果你需要做访问控制，可以配置allow和deny这两个参数
        #deny优先于allow，如果在deny列表中，就算在allow列表中，也会被拒绝。如果allow没有配置或者为空，则允许所有访问
        #配置的格式：<IP> 或者 <IP>/<SUB_NET_MASK_size>其中128.242.127.1/24
        #24表示，前面24位是子网掩码，比对的时候，前面24位相同就匹配,不支持IPV6。
        #deny:xxx
        #allow: 127.0.0.1
      aop-patterns: com.example.demo.*.*.* # 对内部各接口调用的监控
  redis:
    database: 10 # Redis数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    ssl: false
    lettuce:
      pool:
        max-active: 50 # 连接池最大连接数（使用负值表示没有限制）
        max-wait-millis: 10000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        timeout: 0 # 连接超时时间（毫秒）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        test-on-borrow: true # 调用者获取链接时，是否检测当前链接有效性
        test-on-return: true # 向链接池中归还链接时，是否检测链接有效性
        test-while-idle: true # 调用者获取链接时，是否检测空闲超时, 如果超时，则会被移除
        time-between-eviction-runs-millis: 30000 # 空闲链接检测线程检测周期（使用负值表示不运行检测线程）
        num-tests-per-eviction-run: 10 # 空闲链接检测线程一次运行检测多少条链接
        min-evictable-idle-time-millis: 60000 # 连接在池中最小的生存时间

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.demo.dal
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:logback-config.xml
  file:
    path: /users/alfred
  level:
    all: info
    root: info